### ISSUE TITLE
How to put it in .profile?

### ISSUE THREAD

**Issue by cvladan** [CzBiX/WSLHostPatcher#1]
Hi, thanks for this tool!

I'm not exactly sure how to put it in `.profile`?
Is `WSLHostPatcher.exe` executed in Powershell/cmd aka "outside" of WSL2 or inside of WSL2?

**Comment by CzBiX** [comment]
Put files in somewhere, such as `C:\tools\`.
then add this line into your `~/.profile` in WSL2:
`/mnt/c/tools/WSLHostPatcher.exe`

**Comment by cvladan** [comment]
Thanks!

**Comment by darth-j** [comment]
![image](https://user-images.githubusercontent.com/25424615/157695558-1f492b09-c107-4787-88b7-b82efb818645.png)
我在wsl2里面的.profile 添加了/mnt/c/tools/WSLHostPatcher.exe 但是没有起到作用，但是在Windows中运行WSLHostPatcher.exe是有效的，我的Windows版本为21h2 wsl2为kali

**Comment by dennis-gonzales** [comment]
> Put files in somewhere, such as `C:\tools\`. then add this line into your `~/.profile` in WSL2: `/mnt/c/tools/WSLHostPatcher.exe`

I was having difficulties running my expo react native project until I saw this, thanks!

**Comment by gabrielizalo** [comment]
Is it feasible to check if `WSLHostPatcher.exe` is running?
I've already added it to my **WSL2** `/.profile` and I'm still getting the **Expo Android App** error: `Network response timed out`.
