### ISSUE TITLE
Not sure if this is possible...

### ISSUE THREAD

**Issue by meluvalli** [CzBiX/WSLHostPatcher#12]
I am trying to use WSLHostPatcher for HomeKit accessory.    This utility doesn't work because I need to be able to broadcast Bonjour or CIAO packets from WSL.  Is there a way to have this do that or no?

**Comment by CzBiX** [comment]
Check out experimental bridge solution at https://github.com/microsoft/WSL/issues/4150#issuecomment-1018524753.
