### ISSUE TITLE
UDP support

### ISSUE THREAD

**Issue by NickClark** [CzBiX/WSLHostPatcher#2]
First of all... thanks for this! 

Unfortunately only half my issue is solved. It appears UDP doesn't work. Is that expected?

**Comment by CzBiX** [comment]
Yes, the port relay provide by MS is only support TCP.
You have to use others workaround that can modify the Hyper-V netadapter to bridge mode.

**Comment by NickClark** [comment]
I was wondering if there was a way to change the adapter... but I hadn't seen anyone else do it. I'll look further into that option.

Thanks!
