### ISSUE TITLE
remote request ip become to localhost

### ISSUE THREAD

**Issue by NightmareZero** [CzBiX/WSLHostPatcher#20]
hostpatcher will cause the IP address of all network requests sent to WSL to become localhost.

所有来自远程的请求，其ip地址都变成了localhost

![Untitled](https://github.com/CzBiX/WSLHostPatcher/assets/17422155/43f8e8c8-ac98-428c-a6c5-0479ee2561a1)

**Comment by CzBiX** [comment]
it's by desgin.
