### ISSUE TITLE
There is no way to install. There's no `WSLHostPatcher.exe` file nor any other executable.

### ISSUE THREAD

**Issue by jdunk** [CzBiX/WSLHostPatcher#6]
The README says "Run WSLHostPatcher.exe after WSL2 started," but there is no such file (nor any exe) in the repo... not even in the `exe` folder.

How to install?

**Comment by jdunk** [comment]
There is a `WSLHostPatcher.sln` file, but it's not executable.

**Comment by CzBiX** [comment]
#5
