### ISSUE TITLE
Only listening on 127.0.0.1

### ISSUE THREAD

**Issue by mingue** [CzBiX/WSLHostPatcher#7]
Hi! I tried your solution as it seems the cleanest approach, but so far I haven't had any luck. Maybe you have an idea what might be happening.

sshd is running on WSL2 instance and I tried from the windows host and I can do ssh to linux fine

No luck from other machines on my network though, I disabled the firewall on Windows just in case but still the same

This is the output that I get from netstat, shouldn't this be listening on 0.0.0.0:22

```
netstat -an | grep :22
  TCP    127.0.0.1:22           0.0.0.0:0              LISTENING
  TCP    [::1]:22               [::]:0                 LISTENING
```

After reading some of the issues, I wasn't sure where to run the patch, windows or wsl, but it seems that doesn't matter I get the same output, although nothing seems to work

```
Dll path: C:\bin\WSLHostPatch.dll
Found 2 WSL host
Patched 2
```

**Comment by CzBiX** [comment]
You need to listen port after run the patch.
please try to restart sshd service.

**Comment by mingue** [comment]
That makes sense, thanks for the clarification, it's working now 😊

I also created the following script that I use on the task scheduler once I log on. Nothing fancy but I think it clarifies the usage for the patch.

```pwsh
wsl -d Manjaro echo "Starting WSL"
C:\bin\WSLHostPatcher.exe
wsl -d Manjaro genie -i # Start Systemd on the background and exit
```

Forces to start my distro with a simple message
Runs the patcher to bind to the wslhost process
Starts systemd in my case which starts the relevant services, update this for your service initializacion process if different
